[colors.bright]
black = "#7f7f7f"
blue = "#5f5fff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#0000ee"
cyan = "#00cfcf"
green = "#00cf00"
magenta = "#cf00cf"
red = "#cf0000"
white = "#efefef"
yellow = "#cfcf00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 11.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
opacity = 0.85
